name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish .NET Core app
        run: |
          dotnet publish -c Release -o publish_output

      - name: Archive published app
        run: |
          cd publish_output
          zip -r ../publish.zip .
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifact
          path: publish.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-artifact
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E9EB28A037BE48329E28183E32D4F0A1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A0EED8B0E4241F296D13F0078441FA9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C45CD672D9DD4B0884A903806AC3E14A }}

      - name: Wait before deploy to avoid Kudu race conditions
        run: sleep 30

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'setstats'
          slot-name: 'Production'
          package: publish.zip
